SCOOP-19037 Ginti_web_to_store_current_value_of_the_service
scoperetail-io/ginti-core pull request #4
Opened 2022-12-05 12:09 UTC by rajesh-parjapati

2022-12-12 13:34 UTC, vishwanath-mathapati-scope commented on src/main/java/com/scoperetail/commons/ginti/entity/Service.java
> +  @Column(name = "current_seq_value")
change to current_val

2022-12-12 13:35 UTC, vishwanath-mathapati-scope commented on src/main/java/com/scoperetail/commons/ginti/model/ServiceRequest.java
> +    private int count;
change it to fetchCount

2022-12-12 13:38 UTC, vishwanath-mathapati-scope commented on src/main/java/com/scoperetail/commons/ginti/model/Response.java
> +public class Response {
Lets create another response class instead of using old one.

2022-12-12 13:39 UTC, vishwanath-mathapati-scope requested changes
Please work on review comments

2022-12-12 14:13 UTC, vishwanath-mathapati-scope commented on src/main/java/com/scoperetail/commons/ginti/model/ServiceRequest.java
> +    private String service;
Add validation rules here

2022-12-14 09:19 UTC, RakshantScopeRetail commented
@vishwanath-mathapati-scope @rajesh-parjapati Please use branch JDK-11 as main branch for cosmos, master has been upgraded to JDK-17

2022-12-14 09:23 UTC, vishwanath-mathapati-scope commented
> @vishwanath-mathapati-scope @rajesh-parjapati Please use branch JDK-11 as main branch for cosmos, master has been upgraded to JDK-17

Noted. @RakshantScopeRetail Thanks.
@rajesh-parjapati make a note of this

2022-12-15 06:18 UTC, RakshantScopeRetail commented on pom.xml
> +    <version>0.2-SNAPSHOT</version>
change version to 0.1.1-SNAPSHOT

2022-12-15 06:24 UTC, RakshantScopeRetail requested changes
Request changes

2022-12-21 10:37 UTC, closed without merging